config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  get "tasks", to: "tasks#index"
  get "tasks/:id/edit", to: "tasks#edit"
  patch "tasks/:id", to: "tasks#update"

  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"


  get "tasks/:id", to: "tasks#show"

  delete "tasks/:id", to: "tasks#destroy"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ActiveRecord::Base
    validates :title, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    if(@task.save)
      redirect_to tasks_path(@tasks)
    else
      render 'new'
    end
  end

  def update
    @task = Task.find(params[:id])
    if (@task.update(task_params))
    redirect_to tasks_path(@tasks)
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path(@tasks)

  end

  private 
  def task_params
    params.require(:task).permit(:title, :details)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManagerRecode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag '
https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  </head>



  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit an existing task</h1>

<%= form_for :task, url: task_path(@task), method: :patch do |f| %>
<p >
  <%= f.label :title %> 
  <%= f.text_field :title %><br>
</p>

<p>
  <%= f.label :details %>
  <%= f.text_area :details %><br>
</p>

<p>
  <%= f.submit ({:class => 'btn btn-primary'})%>
  </p>
<% end %>


<%= link_to "Task List", tasks_path %>

app/views/tasks/index.html.erb
<div style="margin-bottom: 50px; padding-top: 20px">
    <h1>My Task List</h1> 
</div>

<% @tasks.each do |task| %>

<h3><i class= "fa fa-lg fa-check"> </i>
<%= link_to task.title, task %></h3> 

<%= link_to "Delete", task_path(task), method: :delete %><i class= "fa fa-lg fa-trash"> </i>
<%= link_to "Edit", edit_task_path(task)%><br><hr>
<% end %>


<%= link_to "Add a task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1> Add Task </h1>

<%= form_for :task, url: tasks_path do |f| %>
<p style="">
  <%= f.label :title %> 
  <%= f.text_field :title %><br>
</p>

<p>
  <%= f.label :details %>
  <%= f.text_area :details %><br>
</p>

<p>
  <%= f.submit({:class => 'btn btn-primary'})%>
  </p>
<% end %>

 <%# ({class => 'btn btn-primary'}) %>

app/views/tasks/show.html.erb
<div style="margin: 40px;">
    <h1>Task Selected</h1> 
</div>

<div class="container">
    <h3><%= @task.title %></h3><br>
    <h5><%= @task.details %></h5><br>
</div>
<hr>

<%= link_to "Task List", tasks_path %>